config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :properties

  get '/accounts', to:"admin#accounts", as: :accounts
  get 'dashboard/index', to:"dashboard#index", as: :dashboard
  get '/profile/:id', to:"dashboard#profile", as: :profile
  get '/contact/:id', to:"properties#contact", as: :contact
  post '/agent/message', to:"properties#email_agent", as: :email_agent




  root 'public#main'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
         mount_uploader :image, PhotoUploader
  has_many :properties
  def full_name
    "#{first_name} #{last_name}"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :account

  scope :latest, -> {order created_at: :desc}

  scope :sold, -> {where(for_sale: true, status: "sold") }
  scope :for_sale, -> {where(for_sale: true, status: "available") }
  scope :leased, -> {where(for_sale: false, status: "leased") }
  scope :for_rent, -> {where(for_sale: false, status: "available") }


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :can_access?

  def accounts
   @accounts = Account.where(admin: false)
  end

  def can_access?
   @set_sidebar = true
  unless current_account.admin?
    redirect_to root_url, flash: { danger: "You do not have access to view this page" } and return
  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :url, :image, :image_cache, :comapny, :telephone])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar

  def index
  end

  def profile
    @account = Account.find(params[:id])
    @properties = Property.where(account_id: @account.id)
    @properties_sold = Property.where(account_id: @account.id).sold.count
    @properties_for_sale = Property.where(account_id: @account.id).for_sale.count
    @properties_leased  = Property.where(account_id: @account.id).leased.count
    @properties_for_rent = Property.where(account_id: @account.id).for_rent.count
    @properties_agent = Property.where(account_id: @account.id).where.not(id: @property)

  end

  private
  def set_sidebar
    @set_sidebar = true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new,:create,:destroy]
  before_action :set_sidebar, except: [:show]
  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
    @properties_agent = Property.latest.where('id != ?',params[:id])

  end
  def contact
    @agents = Account.find(params[:id])
  end

  def email_agent
    #trigger an email secondary

    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]
    agent_id = params[:agent_id]
    # response to script
    logger.debug "agent_id : #{agent_id}"
    logger.debug "First name: #{first_name}"
    logger.debug "Last name: #{last_name}"
    logger.debug "Email: #{email}"
    logger.debug "message: #{message}"

      respond_to do |format|
    format.json { head :no_content}
    end
  end
  # GET /properties/new
  def new
    @property = Property.new

  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_sidebar
    @set_sidebar = true
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :room, :bathrooms, :photo, :photo_cache, :parking_spaces, :details, :for_sale, :available_date)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
    if account_signed_in?
      path = current_account.admin? ? accounts_path : dashboard_path
      redirect_to dashboard_path, flash: { success: "Successfully signed in. Welcome to Likair!" } and return
    end
    @property = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_picture account
    thumb = account.image.present? ? account.image.url : "placeholder.jpeg"
    image_tag thumb, class: "profile-pic img-circle "
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_thumbnail property
    img = property.photo.present? ? property.photo.url : "placeholder.jpeg"
    image_tag img, class: "img-thumbnail rounded"
  end
  def property_photo property
    property.photo.present? ? property.photo.url :  assets("placeholder.jpeg")
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/accounts.html.erb
<h2>Accounts</h2>
<% @accounts.each do |account| %>
<div class="row">
  <div class="col-sm-3">
    <%= account.full_name %>
  </div>
  <div class="col-sm-3">
    <%= account.email %>
  </div>
  <div class="col-sm-3">
    <%= account.created_at.strftime("%d/%m/%Y") %>
  </div>
  <div class="col-sm-3">
    <%= link_to "View Profile", profile_path(account.id) %>
  </div>
</div>
<% end %>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container mt-5">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2021 Likair Inc.</p>
  </footer>

app/views/layouts/nav/_admin.html.erb
<li class="nav-item">
  <%= link_to accounts_path, class: "nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
    Accounts
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
    properties
  <% end %>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
    Blog posts
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
    Adverts
  </a>
</li>

app/views/layouts/nav/_dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input style="background: #21252a;border: 1px solid #1b1b1b;" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "nav-link" %>

    </li>
  </ul>
</header>
<%= render 'layouts/nav/sidebar'%>

app/views/layouts/nav/_public.html.erb
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Likair</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to "Dashboard",dashboard_path,class: "nav-link " %>
          <% else %>
              <%= link_to "Home" ,root_path,class: "nav-link " %>
          <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Latest</a>
          </li>
          <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
          </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Advertising</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
         <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }" %>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Setting</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <%= link_to profile_path(current_account), class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
              My profile
              <% end %>
          </li>

          <li class="nav-item">
            <%= link_to edit_account_registration_path, class: "nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
              Account Setting
              <% end %>
          </li>

        </ul>
      </div>
    </nav>

app/views/layouts/nav/_user.html.erb
<li class="nav-item">
  <%= link_to dashboard_path, class: "nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
    Dashboard
  <% end %>
</li>
<li class="nav-item">
  <%= link_to properties_path, class: "nav-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
    properties
  <% end %>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
    Products
  </a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
    Contact
  </a>
</li>

app/views/properties/_agent_details.html.erb
<div class="text-center border pt-4 pb-4 ml-3">
  <%= profile_picture  agent %>
  <h3 class="h4"><%=  agent.full_name %></h3>

  <p><%=  agent.comapny %></p>

  <a class="btn btn-success" href="tel:<%=  agent.telephone %>">Call</a>

  <%= link_to "Profile" ,profile_path( agent.id),class:"btn btn-warning"%>
  
  <%= link_to "Email" ,contact_path( agent.id),class:"btn btn-info"%>

app/views/properties/_latest_properties.html.erb
<%   @property.each do |property| %>
  <div class="col-4 border">
    <%= link_to(property_thumbnail(property), property_path(property)) %>

    <div class="amenities mt-4 mb-4">
      <h3 class="h5 mt-3 "><%=link_to property.name,property_path(property) %></h3>

      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck-flatbed" viewbox="0 0 16 16">
        <path
          d="M11.5 4a.5.5 0 0 1 .5.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-4 0 1 1 0 0 1-1-1v-1h11V4.5a.5.5 0 0 1 .5-.5zM3 11a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm1.732 0h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4a2 2 0 0 1 1.732 1z"/>
      </svg> <%= property.room %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart" viewbox="0 0 16 16">
        <path
          d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z"/>
      </svg> <%= property.bathrooms %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart" viewbox="0 0 16 16">
        <path
          d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z"/>
      </svg> <%= property.parking_spaces %>
          <p class="text-muted "><%= property.address %></p>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1 class="h2">Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h2">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Price</th>
      <th scope="col">Room</th>
      <th scope="col">Bathrooms</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.room %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property,class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_property_path(property),class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-success" %>

app/views/properties/new.html.erb
<h1 class="h2" >New Property</h1>

<%= render 'form', property: @property %>
<br>
<div class="form-group">
  <%= link_to 'Back', properties_path,class:"btn btn-outline-success" %>

</div>

app/views/properties/show.html.erb
<div class=" property-main-photo" style="background-image:url('<%= property_photo @property %>')">
  <div class="photo-overlay"></div>
</div>
<div class="col-12">
  <div class="container mt-5">
    <div class="row">
      <div class="col-sm-8">
        <div class="row">
          <div class="col-sm-6">
            <p class="h4 mb-2"><%= @property.for_sale? ? "For Sale" : "For Rent" %></p>
            <p class="mb-2"><%= @property.address %></p>
            <p class="h2 ">
              <% if @property.for_sale? %>
                <%= @property.price > 0 ? number_to_currency(@property.price, precision:0) : "Offers Accepted" %>
              <% else %>
                <%= @property.price > 0 ? number_to_currency(@property.price, precision:0) : "Open For Enquiries" %>/ Monthly
              <% end %>
            </p>
          </div>
          <div class="col-sm-6">
            <div class="row">
              <div class="col-4 text-center">
                <small>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck-flatbed" viewbox="0 0 16 16">
                    <path
                      d="M11.5 4a.5.5 0 0 1 .5.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-4 0 1 1 0 0 1-1-1v-1h11V4.5a.5.5 0 0 1 .5-.5zM3 11a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm1.732 0h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4a2 2 0 0 1 1.732 1z"/>
                  </svg><br>
                  <%= @property.room %>
                  Rooms</small>
              </div>
              <div class="col-4 text-center">
                <small>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart" viewbox="0 0 16 16">
                    <path
                      d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z"/>
                  </svg><br>
                  <%= @property.bathrooms %>
                  Bathrooms</small>
              </div>
              <div class="col-4 text-center">
                <small>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-minecart" viewbox="0 0 16 16">
                    <path
                      d="M4 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm0 1a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM.115 3.18A.5.5 0 0 1 .5 3h15a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 14 12H2a.5.5 0 0 1-.491-.408l-1.5-8a.5.5 0 0 1 .106-.411zm.987.82 1.313 7h11.17l1.313-7H1.102z"/>
                  </svg><br>
                  <%= @property.parking_spaces %>
                  Parking</small>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5 border-top border-bottom pt-4 pb-4 pd-4 mt-4 mb-4">
          <div class="col-6 ">
            <% if @property.for_sale? %>
              <strong class="text-success">Est. Monthly Repayments of
                <%= number_to_currency(( @property.price - (@property.price * 0.1)) / 360, precision: 0) %></strong>
            <% else %>
              <strong class="text-success">Available from
                <%= @property.available_date.strftime("%a") %>,
                <%= @property.available_date.day.ordinalize %>
                <%= @property.available_date.strftime("%b") %></strong>
            <% end %>
          </div>
          <div class="col-6">
            <strong style="float: right;"><%= link_to "Can i afford this property","#",class: "text-success" %></strong>
          </div>
        </div>
      </div>
      <div class="col-4 mt-0">
        <%= render "properties/agent_details", agent: @agent%>
      </div>
    </div>
    <div class="col-sm-8 mt-2">
      <p class="h3"><%= @property.name %></p>
      <p class="h5 mt-2">Property Description</p>
      <div id="prop-details">
        <%= simple_format @property.details %>
      </div>
      <button type="button" class="btn btn-info m-2" id="toggleDetails">Show more</button>
      <p>* This rate is based on a 30 years mortgage,after paying an initial 10% down payment</p>
      <!-- <%= link_to 'Edit', edit_property_path(@property) %> | <%= link_to 'Back', properties_path %>-->
    </div>
  </div>
</div>
<section class="mt-5 mb-5">
  <div class="container">
    <div class="row">

      <p class="h3 mb-3">Lastest properties</p>
        <%= render "properties/list" %>

    </div>
  </div>
</section>